### ISSUE TITLE
Unable to run on Windows due to gunicorn dependency on fcntl

### ISSUE THREAD

**Issue by leetfin** [infinityofspace/jellyfin_alexa_skill#101]
### Describe the bug

[comment]: <> (A clear and concise description of what the bug is.)

fcntl dependency is not available on Windows, so application is unrunnable. This should at least be disclosed if intentional.

### To Reproduce

[comment]: <> (Steps to reproduce the behavior.)

Install on windows via pip and run application.

### Expected behavior

[comment]: <> (A clear and concise description of what you expected to happen.)

Program to start.

### Versions

[comment]: <> (Please complete the following version information.)

Pip package.
```
Name: jellyfin-alexa-skill
Version: 0.3.1
Summary: Selfhosted Alexa media player skill for Jellyfin
Home-page: https://github.com/infinityofspace/jellyfin_alexa_skill
Author: infinityofspace
Author-email:
License: MIT
Location: c:\program files\python310\lib\site-packages
Requires: ask-smapi-model, ask-smapi-sdk, flask-ask-sdk, Flask-WTF, gunicorn, peewee, pyngrok
Required-by:

```
### Additional context

[comment]: <> (Add any other context about the problem here. E.g. Logs and error messages.)

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\jellyfin_alexa_skill.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python310\lib\site-packages\jellyfin_alexa_skill\main.py", line 21, in <module>
    from gunicorn.app.base import BaseApplication
  File "C:\Program Files\Python310\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "C:\Program Files\Python310\lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by mightyenigma** [comment]
I have the same problem now, after commenting out the import of Markup (which is missing) and changing imports of url_encoder to urlencoder to fix other problems.
Now I get No module named 'fcntl' too.

pip show gunicorn
20.1.0

So I tried
pip install fcntl
ERROR: Could not find a version that satisfies the requirement fcntl (from versions: none)
ERROR: No matching distribution found for fcntl

I'm starting to think the python implementation only works in Linux and not Windows?
Sad day for me - I have a Windows 10 computer and I went through all the setup steps the best I could. It wouldn't kill me to get a Linux system, but all my Jellyfin media is on my Windows system.

**Comment by oberluz** [comment]
Could be. I installed the Linux versión on Ubuntu 24.04. Can't speak for Windows sorry
