### ISSUE TITLE
Error while updating skill manifest

### ISSUE THREAD

**Issue by rikman122** [infinityofspace/jellyfin_alexa_skill#39]
### Describe the bug

[comment]: <> (A clear and concise description of what the bug is.)

There is an error while updating the skill manifest on a clean first start. The interaction model is uploaded correctly as I can see it in the Alexa dev console so I guess that connection parameters to AWS are ok. I tried both docker container and python package version with the same error.

### To Reproduce

[comment]: <> (Steps to reproduce the behavior.)

1. Install the docker or python version like stated in the wiki
2. Create an skill and complete skill.conf
3. Run the container/package and see logs

### Expected behavior

[comment]: <> (A clear and concise description of what you expected to happen.)

The container/package starts correctly and the skill server is running

### Versions

[comment]: <> (Please complete the following version information.)

 - Are you using the Docker image or the Python package?: both
 - jellyfin_alexa_skill: 0.3.1

### Additional context

[comment]: <> (Add any other context about the problem here. E.g. Logs and error messages.)

INFO:Cloud skill version: 

Current skill version: 0.3.1

INFO:Updating skill interaction model...

INFO:Skill interaction model updated

INFO:Updating skill manifest...

Traceback (most recent call last):

File "/opt/venv/bin/jellyfin_alexa_skill", line 33, in <module>

sys.exit(load_entry_point('jellyfin-alexa-skill==0.3.1', 'console_scripts', 'jellyfin_alexa_skill')())

File "/opt/venv/lib/python3.10/site-packages/jellyfin_alexa_skill-0.3.1-py3.10.egg/jellyfin_alexa_skill/main.py", line 353, in main

update_skill_manifest(config,

File "/opt/venv/lib/python3.10/site-packages/jellyfin_alexa_skill-0.3.1-py3.10.egg/jellyfin_alexa_skill/main.py", line 218, in update_skill_manifest

smapi_client.update_skill_manifest_v1(skill_id=skill_id,

File "/opt/venv/lib/python3.10/site-packages/ask_smapi_model/services/skill_management/skill_management_service_client.py", line 12500, in update_skill_manifest_v1

api_response = self.invoke(

File "/opt/venv/lib/python3.10/site-packages/ask_sdk_model_runtime/base_service_client.py", line 143, in invoke

raise ServiceException(message=exception_metadata.message,

ask_sdk_model_runtime.exceptions.ServiceException: Server cannot process the request due to a client error.

**Comment by rikman122** [comment]
Nevermind I was setting the skill url without https
